export const statesData = {
  AL: { name: 'Alabama', capital: 'Montgomery', population: '5,074,296' },
  AK: { name: 'Alaska', capital: 'Juneau', population: '733,583' },
  AZ: { name: 'Arizona', capital: 'Phoenix', population: '7,359,197' },
  AR: { name: 'Arkansas', capital: 'Little Rock', population: '3,045,637' },
  CA: { name: 'California', capital: 'Sacramento', population: '39,029,342' },
  CO: { name: 'Colorado', capital: 'Denver', population: '5,877,610' },
  CT: { name: 'Connecticut', capital: 'Hartford', population: '3,626,205' },
  DE: { name: 'Delaware', capital: 'Dover', population: '1,018,396' },
  FL: { name: 'Florida', capital: 'Tallahassee', population: '22,244,823' },
  GA: { name: 'Georgia', capital: 'Atlanta', population: '11,029,227' },
  HI: { name: 'Hawaii', capital: 'Honolulu', population: '1,440,196' },
  ID: { name: 'Idaho', capital: 'Boise', population: '1,939,033' },
  IL: { name: 'Illinois', capital: 'Springfield', population: '12,582,032' },
  IN: { name: 'Indiana', capital: 'Indianapolis', population: '6,833,037' },
  IA: { name: 'Iowa', capital: 'Des Moines', population: '3,200,517' },
  KS: { name: 'Kansas', capital: 'Topeka', population: '2,937,150' },
  KY: { name: 'Kentucky', capital: 'Frankfort', population: '4,512,310' },
  LA: { name: 'Louisiana', capital: 'Baton Rouge', population: '4,590,241' },
  ME: { name: 'Maine', capital: 'Augusta', population: '1,395,722' },
  MD: { name: 'Maryland', capital: 'Annapolis', population: '6,164,660' },
  MA: { name: 'Massachusetts', capital: 'Boston', population: '6,981,974' },
  MI: { name: 'Michigan', capital: 'Lansing', population: '10,034,113' },
  MN: { name: 'Minnesota', capital: 'Saint Paul', population: '5,717,184' },
  MS: { name: 'Mississippi', capital: 'Jackson', population: '2,961,279' },
  MO: { name: 'Missouri', capital: 'Jefferson City', population: '6,177,957' },
  MT: { name: 'Montana', capital: 'Helena', population: '1,122,867' },
  NE: { name: 'Nebraska', capital: 'Lincoln', population: '1,978,379' },
  NV: { name: 'Nevada', capital: 'Carson City', population: '3,177,772' },
  NH: { name: 'New Hampshire', capital: 'Concord', population: '1,395,231' },
  NJ: { name: 'New Jersey', capital: 'Trenton', population: '9,261,699' },
  NM: { name: 'New Mexico', capital: 'Santa Fe', population: '2,117,522' },
  NY: { name: 'New York', capital: 'Albany', population: '19,677,151' },
  NC: { name: 'North Carolina', capital: 'Raleigh', population: '10,698,973' },
  ND: { name: 'North Dakota', capital: 'Bismarck', population: '779,094' },
  OH: { name: 'Ohio', capital: 'Columbus', population: '11,785,935' },
  OK: { name: 'Oklahoma', capital: 'Oklahoma City', population: '4,019,800' },
  OR: { name: 'Oregon', capital: 'Salem', population: '4,240,137' },
  PA: { name: 'Pennsylvania', capital: 'Harrisburg', population: '12,972,008' },
  RI: { name: 'Rhode Island', capital: 'Providence', population: '1,093,734' },
  SC: { name: 'South Carolina', capital: 'Columbia', population: '5,282,634' },
  SD: { name: 'South Dakota', capital: 'Pierre', population: '909,824' },
  TN: { name: 'Tennessee', capital: 'Nashville', population: '7,051,339' },
  TX: { name: 'Texas', capital: 'Austin', population: '30,029,572' },
  UT: { name: 'Utah', capital: 'Salt Lake City', population: '3,380,800' },
  VT: { name: 'Vermont', capital: 'Montpelier', population: '647,064' },
  VA: { name: 'Virginia', capital: 'Richmond', population: '8,683,619' },
  WA: { name: 'Washington', capital: 'Olympia', population: '7,785,786' },
  WV: { name: 'West Virginia', capital: 'Charleston', population: '1,775,156' },
  WI: { name: 'Wisconsin', capital: 'Madison', population: '5,892,539' },
  WY: { name: 'Wyoming', capital: 'Cheyenne', population: '576,851' }
};
